### ISSUE TITLE
Release to pypi

### ISSUE THREAD

**Issue by saily** [robgolding/django-celery-progress#1]
Hi, would you mind releasing your app to pypi?

**Comment by robgolding** [comment]
Hey! Sure, I always intended to but didn't quite get it finished. Are you using it, out of curiosity?

**Comment by saily** [comment]
Checking out from git is ok for testing, but if i decide to use it, i need an exact version pin i can put into my `requirements.txt` file.

**Comment by Tthomas63** [comment]
Any updates on releasing to pypi?

**Comment by robgolding** [comment]
Sorry, I don't really have time to maintain this project as a Python package. It's never really been finished, and would need bringing up to date with the latest version of Django and Python 3.x support. Feel free to fork and publish to PyPI though!
